// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZqS7ezLsh9ykA5ZsTX9wLuoRlXA9Vyo8',
    appId: '1:432315004437:web:8c662cfb9b38b94f3c801c',
    messagingSenderId: '432315004437',
    projectId: 'hospify-f4c44',
    authDomain: 'hospify-f4c44.firebaseapp.com',
    storageBucket: 'hospify-f4c44.appspot.com',
    measurementId: 'G-9TY023SR84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDftixylH2oqn4OlLSvadep1-nvKDl8CcI',
    appId: '1:432315004437:android:5686a68715a3d40d3c801c',
    messagingSenderId: '432315004437',
    projectId: 'hospify-f4c44',
    storageBucket: 'hospify-f4c44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqwsVadu7CzxIYbhEqyxbJfX9iNo7Aj1w',
    appId: '1:432315004437:ios:158db3a50f897cbe3c801c',
    messagingSenderId: '432315004437',
    projectId: 'hospify-f4c44',
    storageBucket: 'hospify-f4c44.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqwsVadu7CzxIYbhEqyxbJfX9iNo7Aj1w',
    appId: '1:432315004437:ios:69fee517e05010df3c801c',
    messagingSenderId: '432315004437',
    projectId: 'hospify-f4c44',
    storageBucket: 'hospify-f4c44.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
